spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/cyberready
spring.datasource.username=elizaveta
spring.datasource.password=abrikos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect